// Lấy danh sách user
GET http://localhost:3001/users HTTP/1.1

###

// Lấy thông tin user theo ID
GET http://localhost:3001/users/j2B5GYRa HTTP/1.1

###

// Tạo user mới
POST http://localhost:3001/users HTTP/1.1
Content-Type: application/json

{
    "full_name" : "Nguyen Van A",
    "email" : "abc@gmail.com",
    "phone" : "1234523131"
}

###

// Cập nhật thông tin user
PUT http://localhost:3001/users/lswbqrlt HTTP/1.1
Content-Type: application/json

{
    "full_name" : "Ngo Thi B",
    "email" : "465@gmail.com",
    "phone" : ""
}

###

// Xóa user
DELETE http://localhost:3001/users/lswbqrlt